[package]
name = "stlkm-gui"
version.workspace = true
edition.workspace = true

[[bin]]
name = "stlkm-hub"
path = "src/main.rs"

[build-dependencies]
tauri-build.workspace = true

[dependencies]
stlkm-core.workspace = true
tauri.workspace = true
tauri-plugin-updater.workspace = true
serde.workspace = true
serde_json.workspace = true
